[package]
name = "cosmonaut"
version = "0.0.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
description = ""
license = "MIT"
edition = "2018"

[dependencies]
tui = "0.5"
termion = "1.5"
failure = "0.1"
walkdir = "2"
signal-hook = "0.1.10"
structopt = "0.3"

[dev-dependencies]
insta = "0.12.0"
cargo-insta = "0.11.0"
